<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-5">
                        <h2>Category <b>Management</b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="/admin/message" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New Category</span></a>
                        <a href="#" class="btn btn-secondary"><i class="material-icons">&#xE24D;</i> <span>Export to Excel</span></a>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Порядковый номер</th>
                    <th>Название категории</th>
                    <th>Код категории</th>
                    <th>Количество новостей</th>
                    <th>Настройки категории</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($this->categories as $category) { ?>
                    <tr>
                        <td><?php echo $this->serialNumber; ?> </td>
                        <td>
                            <span class="cat_val"><?php echo $category['cat_name']; ?></span>
                            <form class="category-upload" method="post" action="admin/upload/<?php echo $category['cat_code']; ?>">
                                <input type="text" name="cat_name" value="<?php echo $category['cat_name']; ?>" required>
                                <input class="upload-submit" type="submit" name="upload-submit" value="Ok">
                            </form>
                        </td>
                        <td>
                            <span class="cat_val"><?php echo $category['cat_code']; ?></span>
                            <form class="category-upload"  method="post" action="admin/upload/<?php echo $category['cat_code']; ?>">
                                <input name="cat_code" type="text" value="<?php echo $category['cat_code']; ?>" required>
                                <input class="upload-submit" type="submit" name="upload-submit" value="Ok">
                            </form>
                        </td>
                        <td><?php echo $category['count_news']; ?></td>
                        <td>
                            <a href="/admin/upload/<?php echo $category['cat_code']; ?>" class="settings" title="Редактировать"
                               data-toggle="tooltip"><i class="material-icons">&#xE8B8;</i></a>
                            <a href="/admin/delete/<?php echo $category['cat_code']; ?>" class="delete" title="Удалить"
                               data-toggle="tooltip"><i class="material-icons">&#xE5C9;</i></a>
                        </td>
                    </tr>
                    <?php $this->serialNumber++; ?>
                <?php } ?>

                </tbody>
            </table>
            <div class="clearfix">
                <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
                <ul class="pagination">
                    <li class="page-item disabled"><a href="#">Previous</a></li>
                    <li class="page-item"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">2</a></li>
                    <li class="page-item active"><a href="#" class="page-link">3</a></li>
                    <li class="page-item"><a href="#" class="page-link">4</a></li>
                    <li class="page-item"><a href="#" class="page-link">5</a></li>
                    <li class="page-item"><a href="#" class="page-link">Next</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>