<div class="container">
    <div class="mt-5 row justify-content-center">
        <form class="col-8 needs-validation" action="/admin/create" method="post">
            <div class="mb-3">
                <label for="validationCustom01" class="form-label col-auto">Название категории</label>
                <input type="text" name="cat_name" class="form-control" id="validationCustom01" aria-describedby="emailHelp" required>
            </div>
            <div class="mb-3">
                <label for="validationCustom02" class="form-label col-auto">Код категории</label>
                <input type="text" name="cat_code" class="form-control" id="validationCustom02" aria-describedby="emailHelp" required>
            </div>
            <button type="submit" name="cat_submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>